### PR TITLE
Fix for Xcode 8.3 b5 (8E161) framework "redefinition of module" build errors.

### PR DESCRIPTION
**Pull request by alexkent**
Xcode 8.3 beta 5 (8E161) complains about "module redefinition" when attempting to build BerTlv as a framework. To resolve this I have renamed `module.modulemap` to `BerTlv.modulemap` (apparently `module.modulemap` is magic?).

This change allows Carthage 0.20 to build the BerTlv dynamic framework using the Xcode 8.3 b5 compiler.

### CODE REVIEW

**Comment by evsinev** [comment]
Hi Alex, 

Thank you for your fix.
